// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package token

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseGranteTypeFromString Parse GranteType from string
func ParseGranteTypeFromString(str string) (GranteType, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := GranteType_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown GranteType: %s", str)
	}

	return GranteType(v), nil
}

// Equal type compare
func (t GranteType) Equal(target GranteType) bool {
	return t == target
}

// IsIn todo
func (t GranteType) IsIn(targets ...GranteType) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t GranteType) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *GranteType) UnmarshalJSON(b []byte) error {
	ins, err := ParseGranteTypeFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
